blank_issues_enabled: true
contact_links:
  - name: Feature Requests
    url: https://github.com/timmyfpv/giglrs/discussions/new
    about: Request GIGLRS features in the ideas section of the discussion
